### ISSUE TITLE
Suggestions about improve forecast accuracy

### ISSUE THREAD

**Issue by NoHeartPen** [epistularum/hunspell-ja-deinflection#1]
Sorry, I am a Chinese student, studying Japanese Language and Literature, so my English is not very good, I hope you can forgive the grammatical errors in this sentence.

It looks like you left out some details：

for example:  `形容詞`:
`高そうだ`
According to your point of view, we can find `高い` through `高そ`, but judging from the `.aff` file, you seem to have missed this point (sorry, I[read the hunspell manual](https://github.com/kindernarr/hunspell_in_depth), but I still don't understand what does the `0` do, so I think you're missing this transformation)

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918202955.png)

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918202847.png)

Then it's about `一段動詞`, they all end in る, so a verb like `晩ご飯を食べた`, we should look up `食べた` (if we use `食べ`, we may find `食ぶ`), but it looks like you are ignoring this too:

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918205501.png)

Finally, about `口語`: `すべてのおやつは食べちゃった`, maybe we should use `食べちゃ` instead of `食べち`, because our mouse may not be so accurate.

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918205522.png)

And There are many other special expressions in Japanese, such as katakana:

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918205627.png)

You can refer to this Chinese college student's hunspell file in Github :

[https://github.com/MrCorn0-0/hunspell_ja_JP/](https://github.com/MrCorn0-0/hunspell_ja_JP/)

Although his approach to verbs is not the same as yours, it may help you.

The following are the common word endings in modern Japanese that I have collected: (`五` is a `五段動詞`, and the `一` is a `上一段動詞`, because I am not familiar with `古文`, so it does not include the ancient language)
![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918204229.png)

The above data comes from the "NoJishoKei" project. You can find it in FreeMdict's 《[真·哪里不会点哪里_日本語非辞書形辞典_v2 - 日语 - FreeMdict Forum](https://forum.freemdict.com/t/topic/14048)》 (you just need to put it in the content folder like other mdx, when your clipboard is `食べた`,  it will give a hyperlink that can jump to `食べる`  ).

You can also learn more on GitHub:

[https://github.com/NoHeartPen/NonJishoKei](https://github.com/NoHeartPen/NonJishoKei)

> It is a development project dedicated to providing the best clipboard word search experience, and currently, there is a `日本語非辞書形辞典.mdx` and 2 scripts use Python and JavaScript languages (sorry, The software used in the two scripts are all developed by Chinese, and it may be inconvenient for foreigners to use. I will submit a PR on [Saladict](https://saladict.crimx.com/en/) in the future. Saladict is an online dictionary add-ons like youmichan, but you can use Weblio and Weblio 英和和英辞典)

Finally, it's really nice to meet someone who has the same idea as me, I hope you can achieve the best clipboard word lookup experience on Goldendict with Hunspell :)

# 中文原文

提高预测的准确性

不好意思，我是一名日语专业的中国大学生，我的英语不是很好，希望您能原谅我的语法错误。

看起来您忽略了很多细节，比如`形容詞`：
`高そうだ`
按照您的观点，我们可以通过`高そ`查到`高い`，但是从`.aff`文件来看，您似乎遗漏了这一点（不好意思，我阅读了 hunspell 的手册，还是没有搞懂这里的`0`有什么作用，所以认为您是遗漏了这个变形）

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918202955.png)

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918202847.png)

然后是关于`一段動詞`，它们的词尾假名都是る，所以像`晩ご飯を食べた`这样的动词，我们应该划`食べた`（如果用`食べ`，我们可能查到的是`食ぶ`），但看起来您也忽略了这一点：

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918205501.png)

最后是关于口语的表达：`すべてのおやつは食べちゃった`，也许我们应该用`食べちゃ`，而不是`食べち`，因为我们的鼠标可能没有那么准确。

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918205522.png)

日语还有很多其他特殊的表达，比如片假名：

![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918205627.png)

您可以参考这位中国大学生的 hunspell 文件：

[https://github.com/MrCorn0-0/hunspell_ja_JP/](https://github.com/MrCorn0-0/hunspell_ja_JP/)

虽然他对于动词的处理原则和您不太一样，但应该对您有所帮助。

以下是我搜集的在现代日语中常见的的词尾变换：（`五`是`五段動詞`，`一`是`上一段動詞`，由于我不太熟悉`古文`，所以并不包含古语）
![|500](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220918204229.png)

以上的数据来自《日本語非辞書形辞典》项目，您可以在 FreeMdict《[真·哪里不会点哪里_日本語非辞書形辞典_v2 - 日语 - FreeMdict Forum](https://forum.freemdict.com/t/topic/14048)》（您只需要像使用其他 mdx 放到 content 文件夹即可，它会在您的剪贴板是`食べた`的时候给出一个可以跳转到`食べる`的超链接）。

您也可以在 GitHub 上了解更多信息：

它是一个致力于提供最好的剪贴板查词体验的开发计划，目前已经有一个`日本語非辞書形辞典.mdx`和 2 个分别使用了 Python 和 JavaScript 语言编写的脚本（很抱歉，这 2 个脚本所用的软件都是中国人开发，外国人使用起来会不太方便，后续我会在以[沙拉查词](https://saladict.crimx.com/en/)上提交 PR，它是一个像 youmichan 的在线词典，但您可以使用 Weblio、Weblio 英和和英）

最后，真的很高兴遇到了和我有同样想法的人，希望您能用构词法在 Goldendict 上实现最棒的剪贴板查词体验:)

**Comment by epistularum** [comment]
@NoHeartPen 

Please excuse for the very late reply, I somehow must have missed the GitHub notification?
It seems like all the questions are related to a misunderstanding of Japanese conjugation/inflection. (My native language is also not English so bear with me)

### 1. 高そうだ
The construction of this example is the root (語幹) of the adjective combined with そうだ. Here is the relevant dictionary entry for this grammatical point:
![image](https://github.com/epistularum/hunspell-ja-deinflection/assets/34507493/0b668035-d6db-4860-8ee9-2428dfcd261e)

### 2. 一段動詞
All forms for this verb class are the same, only the る part is removed. Please refer to the table below.
For a more concrete example:
書いた: 書い(連体形 of 書く) + た(inflectional suffix)
食べた: 食べ(連体形 of 食べる) + た(inflectional suffix)
The inflectional suffix (助動詞) is not part of the verb base, it's just a suffix to the verb base.
![image](https://github.com/epistularum/hunspell-ja-deinflection/assets/34507493/833078d8-8504-47bc-85f1-cf58b5de1779)
![image](https://github.com/epistularum/hunspell-ja-deinflection/assets/34507493/39a19fe8-f126-4b93-9d5b-a5983de6a903)

### 3. 食べちゃ
The construction here is once again just the verb base 食べ + the inflectional suffix ちゃう. Here is the relevant dictionary entry:
![image](https://github.com/epistularum/hunspell-ja-deinflection/assets/34507493/1e9e15ed-7e71-4317-a586-66ec1a5d2b7f)

### 4. Alternate spelling
Alternate spelling of words such as チョロチョロ instead of ちょろちょろ is something that I have though about is outside the scope of this project since it is not related to conjugation. Such a project would require a lot of dedication and time because it would need to cover all these issues:
 - katakana/hiragana alternate spelling: ちょろちょろ/チョロチョロ
 - okurigana differences: 取り掛かる/取り掛る
 - 代用字/代用語: 交差/交叉
 - 混ぜ書き: 豹変/ひょう変
 - 拡張新字体: 噓/嘘
 - 旧字体: 潜る/潛る
 - 俗字: 兎/兔
 - 異体字: 洩/泄
 - 正字: 猫/貓
And so on...

As you you must know, there is huge amount of inflectional suffixes which can be specific to a dialect or a time period. Cataloging all suffixes is an impossible task as you would not only have to catalog all possible past and historical declinations but also all regional dialects. To go around this issue, this hunspell dictionary is based on the verb stem which is the common denominator across the Japanese language.

The drawbacks for my method are two fold:
1. Less user friendly. A better understanding of japanese conjugation and verb forms is needed.
2. Might result to a less precise dictionary lookup. For example, if you are faced with 高そう you will need to look up for 高 but this will result in a lot of dictionary entries unrelated to the adjective 高い:
![image](https://github.com/epistularum/hunspell-ja-deinflection/assets/34507493/92e7f1d8-c5b8-4096-ada1-a2fb4276094d)

Advantages:
1. Is able to de-inflect any conjugation in an agnostic way without the need to have each inflectional suffix hardcoded in a de-inflection table.
2. Less bloated


I am aware of your project and I think it's very cool as well. Both methods have merits and demerits, it's up to user preference. I wish you the best of luck in your project!
